[project]
name = "fast-zero"
version = "0.1.0"
description = ""
authors = [
    {name = "esterfeliciano",email = "ester.felicianomelo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard] (>=0.139.2,<0.140.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
